# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=255)),
                ('unique_id', models.CharField(default=uuid.uuid4, max_length=255)),
            ],
        ),
    ]
