# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beacon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='trace',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
